[서버 사이드 렌더링 - 1단계] 에프이(박철민) 미션 제출합니다.
woowacourse/react-ssr pull request #11
Opened 2024-10-08 08:59 UTC by chysis

## 👀 리뷰를 통한 생각 나눔

**1. SSR 렌더링 시 초기 렌더링 성능이 왜 유리할까?**
- 💡 작성 요령
  - 서버가 요청을 받은 순간부터 브라우저에 최종 HTML을 반환할 때까지 어떤 단계가 있는지 파악해야 합니다.
  - 도식화해서 요청과 응답의 흐름을 파악하면 구체적으로 렌더링 방식에 관해 이해할 수 있어요.

### CSR

1. 사용자가 페이지에 접근하면 브라우저는 서버에 요청을 보냅니다.
2. 서버는 껍데기 뿐인 HTML을 반환합니다.
3. 브라우저는 React 및 자바스크립트 파일을 다운로드합니다.
4. 자바스크립트 파일이 로드된 뒤에 HTML을 동적으로 생성하고 DOM을 그립니다.
5. 사용자는 콘텐츠를 볼 수 있게 됩니다.

### SSR

1. 사용자가 페이지에 접근하면 브라우저는 서버에 요청을 보냅니다.
2. 서버는 이미 완성된 HTML을 반환하고, 브라우저는 이를 즉시 파싱해 DOM을 그립니다. 사용자는 콘텐츠를 볼 수 있게 됩니다.
3. 브라우저는 자바스크립트 파일을 다운로드하고, 하이드레이션 과정을 거쳐 상호작용이 가능해집니다.

- SSR은 이미 완성된 HTML을 반환받아 즉시 DOM을 그리기 때문에 사용자는 완성된 콘텐츠를 볼 수 있고, 따라서 초기 렌더링 성능이 우수합니다. 반면 CSR은 자바스크립트 파일을 모두 실행한 뒤에야 DOM을 그리게 됩니다.
- SSR은 하이드레이션을 통해 추가적인 렌더링 딜레이 없이도 상호작용이 가능해집니다. 

**2. 서버에서 렌더링한 영화 목록을 어떻게 클라이언트에 데이터를 전달하고 브라우저에서는 어떤 작업을 수행할까?**
- 💡 작성 요령
  - 서버 측에서 클라이언트 측 컴포넌트 코드를 불러올 때 리액트에서 제공하는 어떤 함수를 사용하고 있는지 파악해 보세요.
  - 브라우저에서 서버로부터 HTML을 받고 난 뒤, 리액트 앱이 로드되면 가장 먼저 어떤 작업을 수행할지와 그 이유에 관해 고민해 보세요.

### renderToString
- 서버에서는 클라이언트의 <App />을 렌더링해서 문자열로 만들어주는 `renderToString` 함수를 사용하고 있습니다.
```js
const renderedApp = renderToString(<App movies={nowPlayingMovies} />);
```

### 리액트 앱이 로드되고 가정 먼저 수행하는 작업
```js
hydrateRoot(document.getElementById('root'), <App movies={initialData.movies} />);
```
- hydrateRoot는 서버에서 이미 렌더링된 HTML과 리액트를 결합합니다. 이를 하이드레이션이라 하며, 가상 DOM과 기존의 DOM이 다르다면 변경된 부분을 다시 렌더링하고 이벤트 리스너 등을 붙여 상호작용 가능하도록 합니다.

**3. 전역 객체 초기화 작업은 왜 진행해야 할까?**
- 💡 작성 요령
  - 아래와 같은 오류가 왜 발생하는지 탐구해 보세요.
  ```text
  react-dom.development.js:86 Warning: An error occurred during hydration. The server HTML was replaced with client content in <div>
  react-dom.development.js:12507 Uncaught Error: Hydration failed because the initial UI does not match what was rendered on the server.
  ```

전역 객체 초기화 작업은 초기에 **서버와 클라이언트가 동일한 상태를 가질 수 있도록** 합니다. 만약 다른 상태를 가지고 있다면 위와 같이 하이드레이션에 실패했다는 에러 메시지가 뜹니다.

```js
const initData = /*html*/ `
    <script>
      window.__INITIAL_DATA__ = {
        movies: ${JSON.stringify(nowPlayingMovies)}
      }
    </script>
  `;
```
서버에서는 전역 객체에 현재 상영 중인 영화 데이터를 저장합니다. 클라이언트는 `__INITIAL_DATA__.movies`에 접근하여 서버와 같은 데이터를 사용할 수 있게 됩니다.

2024-10-09 07:25 UTC, soi-ha requested changes
안녕하세요, 에프이!
제 리뷰가 약간 늦었죵...?ㅎㅎ 기다리게 해드려서 죄송해요!

남겨주신 PR 내용이나 소스코드를 봤을 때, 한가지 정도 궁금한게 있어서 바로 approve는 하지 않았어요. 확인 부탁드려요 :)
그리고 작성해주신 PR 내용 보고 공부하면서 약간 부족했던 기념을 덕분에 채울 수 있었어요~ 간결하지만 핵심만 적혀있어서 이해가 잘 됐어요ㅎㅎ 

제가 남긴 코멘트 한번 확인해주시고 다시 리뷰 요청주시면 이번엔 빠르게 해드릴게요! ☺️

2024-10-09 07:25 UTC, soi-ha commented on src/client/main.js
> +hydrateRoot(document.getElementById('root'), <App movies={initialData.movies} />);
index.html 파일에 root라는 Id는 존재하지 않는데, 혹시 다른 곳에 root id가 존재할까요?

2024-10-09 07:25 UTC, soi-ha commented on src/server/apis/movies.js
> +  } catch (error) {
오, error까지 신경써주셨군요! 👍

2024-10-12 14:16 UTC, chysis commented on src/client/main.js
> +hydrateRoot(document.getElementById('root'), <App movies={initialData.movies} />);
미션 뼈대 코드가 바뀌기 전에 root가 없다는 것을 눈치채지 못했네요😭 root라는 id가 존재하지 않아서 App 컴포넌트와 결합되지 않고, 따라서 지금은 하이드레이션이 일어날 수 없는 상태인 것 같아요.

1단계를 구현할 때 클릭 이벤트를 전부 제거하고 작업해서 제대로 동작하는지 확인하지 못했는데, 2단계 미션 시작할 때 수정된 뼈대 코드 반영해서 작업하겠습니다! 위 PR의 3번 문항은 이론적으로 접근했다고 봐주시면 좋을 것 같아요 :)

2024-10-12 14:32 UTC, soi-ha approved these changes
남겨주신 답글 잘 확인했어요, 에프이!
1단계는 이만 마무리하겠습니다! 
프로젝트 진행하랴 많이 바쁠텐데, 2단계 미션과 같이 화이팅해봅시다~!👍🏻

2024-10-12 14:33 UTC, merged