[서버 사이드 렌더링 - 1단계] 파슬리(김윤아) 미션 제출합니다.
woowacourse/react-ssr pull request #30
Opened 2024-10-10 02:46 UTC by anttiey

안녕하세요, 치코! 🫡 이렇게 미션으로 만나게 되는 건 처음이네요 🚀

이번 단계의 경우 뼈대 코드가 수정되기 전 미션을 진행하여 수정 사항이 반영되어 있지 않는 점 양해 부탁드려요 😭 다음 단계에서 점진적으로 반영해 보도록 할게요!

<hr />

# 👀 리뷰를 통한 생각 나눔

## 1️⃣ SSR 렌더링 시 초기 렌더링 성능이 왜 유리할까?

서버 사이드 렌더링의 초기 렌더링 성능이 유리할 수 있는 이유는 서버가 브라우저 대신 HTML을 미리 생성해 제공하기 때문이라고 생각합니다. 서버 사이드 렌더링의 초기 렌더링 과정을 그림으로 표현하면 다음과 같습니다.

<br />

> <img width="685" alt="image (1)" src="https://github.com/user-attachments/assets/31b11959-e58c-4da7-9db1-c856aeec09ff">

<br />

1. 사용자가 웹 페이지에 접속하면 브라우저가 서버로 요청을 보냅니다.
2. 서버는 요청을 받은 후 필요한 데이터를 비동기로 가져와 HTML을 생성하며, 완성된 HTML을 브라우저에 전달합니다.
3. 브라우저는 받은 HTML을 파싱하여 초기 화면을 구성합니다. 이 단계에서 사용자는 이미 페이지 콘텐츠를 볼 수 있습니다.
4. 이후 브라우저는 필요한 자바스크립트를 로드하고 실행합니다.
5. 자바스크립트가 실행되면서 사용자와의 상호작용이 활성화됩니다.

브라우저가 서버에서 전달받은 HTML을 파싱하고 나면 페이지의 주요 콘텐츠가 화면에 나타나기 때문에, 자바스크립트 실행 시간을 기다릴 필요 없이 초기 렌더링을 빠르게 완료할 수 있습니다. 자바스크립트를 로드한 후 실행하고 데이터 페칭이 완료된 후에야 비로소 콘텐츠가 렌더링되는 CSR 렌더링과 비교했을 때 초기 렌더링에서 유리하다고 말할 수 있습니다.

## 2️⃣ 서버에서 렌더링한 영화 목록을 어떻게 클라이언트에 데이터를 전달하고 브라우저에서는 어떤 작업을 수행할까?

서버는 사용자의 요청을 받아 TMDB 서버로부터 영화 목록 데이터를 가져옵니다. 그런 다음, 이 데이터를 리액트 컴포넌트에 전달하여 `renderToString` 함수를 통해 HTML 문자열로 변환합니다. 이 과정에서 영화 목록이 포함된 완성된 HTML이 만들어지게 됩니다. 서버는 이렇게 생성된 HTML을 클라이언트에 응답으로 전송합니다. 브라우저는 전달받은 HTML을 파싱하여 초기 화면을 구성합니다.

## 3️⃣ 전역 객체 초기화 작업은 왜 진행해야 할까?

```bash
react-dom.development.js:86 Warning: An error occurred during hydration. The server HTML was replaced with client content in <div>
react-dom.development.js:12507 Uncaught Error: Hydration failed because the initial UI does not match what was rendered on the server.
```

해당 문제는 하이드레이션과 밀접한 관계가 있는데요. 현재 코드에서는 위 에러를 마주하지 못해서 개념적으로만 답변하도록 하겠습니다.

첫 번째 경고는 `서버에서 렌더링한 HTML과 클라이언트에서 하이드레이션할 때 HTML 구조가 일치하지 않아 클라이언트가 서버 HTML을 삭제하고 새로 렌더링했음` 을 의미하고, 두 번째 오류는 `서버와 클라이언트의 초기 상태가 일치하지 않아 하이드레이션이 실패했음` 을 나타냅니다.

전역 객체 초기화 작업이 필요한 이유는 클라이언트 측 렌더링이 시작될 때, 서버에서 설정한 상태와 일치하는 상태를 유지해야 하기 때문입니다. 그렇지 않으면 서버와 클라이언트 간의 UI 불일치로 인해 하이드레이션 오류가 발생할 수 있습니다. 전역 객체 초기화를 통해 서버에서 사용한 데이터를 클라이언트의 전역 객체에 저장하면, 클라이언트에서 하이드레이션 시 동일한 데이터를 사용해 일관성을 유지할 수 있습니다. 이를 통해 하이드레이션 오류를 방지하고 서버와 클라이언트 간의 상태를 동기화할 수 있습니다.

2024-10-10 15:03 UTC, jaeml06 commented
안녕하세요! 파슬리 이번 미션 잘 진행해 주셨어요!
3가지 질문에도 이해하기 쉽게 잘 작성했다고 생각해요. 이번 미션은 사전 미션과 딱히 다를게 없어서 추가 요구 사항이 많은 미션이 아니었네요.
제 생각에는 추가된 뼈대 이외에 제가 드릴 요구사항은 없다고 생각합니다.
자잘한 태그에 코멘트를 달았지만 문제는 없다고 생각이 들고요!
일단 request_chage를 드리겠습니다. 혹시 코멘트 받고 싶은 부분이 없다면 appove후 바로 merge해드리겠습니다.

마지막으로 질문을 하자면 파슬리는 언제 SSR을 사용하고 CSR를 사용해야 하는지 궁금하네요

2024-10-10 15:03 UTC, jaeml06 requested changes

2024-10-10 15:03 UTC, jaeml06 commented on src/client/App.jsx
>      <div>
<></>로 변경해도 괜찮을 것 같아요!

2024-10-10 15:03 UTC, jaeml06 commented on src/client/components/MovieItem.jsx
> +    <div className="item">
`<li> `를 쓰지 않고 `div`를 쓴 이유가 있을까요?

2024-10-14 02:09 UTC, anttiey commented on src/client/components/MovieItem.jsx
> +    <div className="item">
큰 이유가 없었습니다 😂 `<li>` 태그로 변경하는 게 좋겠네요 👍

2024-10-14 02:19 UTC, anttiey commented
안녕하세요, 치코! 코멘트 남겨 주셔서 감사해요 🍀

> 마지막으로 질문을 하자면 파슬리는 언제 SSR을 사용하고 CSR를 사용해야 하는지 궁금하네요

위의 질문에는 답변을 하기가 애매한 게 제가 이번 미션을 제외하고는 한 번도 SSR을 사용해 본 적이 없어서 아직 저만의 기준이 뚜렷하지 않아요. 다만, 단순하게 생각해 보면 서버 리소스가 충분하고, 검색 엔진 최적화가 중요한 서비스에는 SSR, 느린 초기 로드 시간을 감당해야 할 정도로 서버 리소스가 부족한 경우에는 CSR을 선택할 것 같네요!

2024-10-14 03:29 UTC, jaeml06 approved these changes
다음 단계에 또 봐요. appove드리겠습니다.

2024-10-14 03:30 UTC, merged