[서버 사이드 렌더링 - 1단계] 헤일리(최혜림) 미션 제출합니다.
woowacourse/react-ssr pull request #31
Opened 2024-10-10 03:48 UTC by healim01

## 👀 리뷰를 통한 생각 나눔

2024-10-10 12:20 UTC, ss0526100 requested changes
안녕하세요 헤일리~ 반갑습니다

템플릿의 질문들도 잘 작성해주셨네요. 덕분에 ssr을 한 번 더 잘 이해할 수 있는 시간이 된 것 같아요.

수정하면 좋을 것 같은 부분 코멘트 남겨놨으니 반영 후 리뷰요청주세요! 바로 달려가겠습니다!!

2024-10-10 12:20 UTC, ss0526100 commented on src/client/App.jsx
>      <div>
이 부분을 따로 div로 감싸신 이유가 궁금해요~

2024-10-10 12:20 UTC, ss0526100 commented on src/client/components/Header.jsx
> +              <span className="rate-value">{round(vote_average, 1)}</span>
round라는 유틸함수를 만드셨군요. 좋은 방법인 것 같아요.

이와 유사한 `Number.toFixed()`라는 함수도 나중에 한 번 찾아보시면 좋을 것 같아요.

2024-10-10 12:20 UTC, ss0526100 commented on src/client/components/MovieItem.jsx
> +          <span>{round(rate)}</span>
이 부분에 두 번째 인자가 들어가지 않고 있는데, 의도하신 부분이 맞는지 확인해보시면 좋을 것 같아요.

2024-10-10 12:20 UTC, ss0526100 commented on src/server/apis/url.js
> +    Authorization: 'Bearer ' + process.env.TMDB_TOKEN,
hydration 과정에서, 클라이언트에 `process.env`가 없기 때문에 에러가 발생해요.
![image](https://github.com/user-attachments/assets/229c1185-3799-4183-934a-4b2f7e104c34)

이 부분을 해결하기 위해서 다음 블로그를 참고하시면 좋을 것 같아요.

https://velog.io/@dea8307/React-webpack%EC%9C%BC%EB%A1%9C-%EA%B5%AC%EC%B6%95%ED%95%9C-React-%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8%EC%97%90%EC%84%9C-%ED%99%98%EA%B2%BD%EB%B3%80%EC%88%98-%EC%A0%81%EC%9A%A9%ED%95%98%EA%B8%B0

client 번들링이 문제이니 client config만 설정해주시면 될 것 같습니다!

2024-10-10 12:20 UTC, ss0526100 commented on views/index.html
> +    <div id="root"></div>
id가 root로 변경되면서 적용되지 못한 css가 존재해요.

main.css에서 다음 id를 root로 바꿔주시면 해결될 것 같아요

```
#wrap {
  min-width: 1440px;
  background-color: var(--color-bluegray-100);
}

#wrap h2 {
  font-size: 1.4rem;
  font-weight: bold;
  margin-bottom: 32px;
}
```

2024-10-10 12:20 UTC, ss0526100 commented on public/styles/main.css
> +.subtitle {
기존 css가 적용되지 않아 따로 class를 주셨네요
눈썰미가 좋으시군요?!?!

2024-10-13 06:10 UTC, healim01 reviewed
안녕하세요 소파~! 
보내주신 코멘트 덕분에 놓쳤던 부분을 잘 수정한거 같습니다! 

반영된 수정사항 한번만 확인해주세요~! 
감사합니다~!

2024-10-13 06:10 UTC, healim01 commented on src/client/App.jsx
>      <div>
기존에 있던 코드라 따로 깊이 생각하지 않고 사용했네요! 불필요한 태그라서 지워도 될거 같습니다~!

2024-10-13 06:10 UTC, healim01 commented on src/client/components/MovieItem.jsx
> +          <span>{round(rate)}</span>
이런 `1` 을 넣었어야 했는데 까먹었네요 눈썰미가 좋으신데요!!

2024-10-13 06:10 UTC, healim01 commented on src/server/apis/url.js
> +    Authorization: 'Bearer ' + process.env.TMDB_TOKEN,
오 왜 이런 문제가 발생하나 했는데 감사해요!

2024-10-13 12:16 UTC, merged