[서버 사이드 렌더링 - 1단계] 초코(강다빈) 미션 제출합니다.
woowacourse/react-ssr pull request #33
Opened 2024-10-10 04:25 UTC by 00kang

## 👀 리뷰를 통한 생각 나눔

1. SSR 렌더링 시 초기 렌더링 성능이 왜 유리할까?
- 💡 작성 요령
  - 서버가 요청을 받은 순간부터 브라우저에 최종 HTML을 반환할 때까지 어떤 단계가 있는지 파악해야 합니다.
  - 도식화해서 요청과 응답의 흐름을 파악하면 구체적으로 렌더링 방식에 관해 이해할 수 있어요.

2. 서버에서 렌더링한 영화 목록을 어떻게 클라이언트에 데이터를 전달하고 브라우저에서는 어떤 작업을 수행할까?
- 💡 작성 요령
  - 서버 측에서 클라이언트 측 컴포넌트 코드를 불러올 때 리액트에서 제공하는 어떤 함수를 사용하고 있는지 파악해 보세요.
  - 브라우저에서 서버로부터 HTML을 받고 난 뒤, 리액트 앱이 로드되면 가장 먼저 어떤 작업을 수행할지와 그 이유에 관해 고민해 보세요.

3. 전역 객체 초기화 작업은 왜 진행해야 할까?
- 💡 작성 요령
  - 아래와 같은 오류가 왜 발생하는지 탐구해 보세요.
    ```
    react-dom.development.js:86 Warning: An error occurred during hydration. The server HTML was replaced with client content in <div>
    react-dom.development.js:12507 Uncaught Error: Hydration failed because the initial UI does not match what was rendered on the server.
    ```

2024-10-11 07:25 UTC, seongjinme requested changes
초코 안녕하세요! 아르입니다. 
레벨2 이후로 오랜만에 인사 드리네요 :)

구현해주신 코드, 그리고 PR 본문으로 공유해주신 답변을 감사히 잘 보았습니다.
특히 각 질문별 답변 내용이 간결하면서도 명료해서, 여기에 대해서는 제가 더 피드백 드릴 내용이 없네요 😅 

다만 코드 레벨에서는 아래와 같은 이슈들이 있었어요.

1. Hydration이 제대로 되지 않고 있어요. 현재 코드로 로컬 실행을 해보면 CSR 없이 SSR로만 동작합니다. 디버깅을 해보니 여러 이슈들이 겹쳐서 발생한 문제로 보이는데, 이에 대해서는 제가 코드 별로 남겨드린 코멘트를 참고하시면 좋겠습니다.
2. `package.json`의 `build:client` 명령어를 따로 설정해주신 것 같은데, 이에 대해서도 궁금한 점이 있어 별도로 코멘트를 드렸습니다.

확인해 보시고 다시 리뷰 요청 해주시면, 빠르게 체크 후 머지해 드릴게요!

2024-10-11 07:25 UTC, seongjinme commented on package.json
> +    "build:client": "if exist dist rmdir /s /q dist && webpack --config webpack.client.config.js",
macOS 환경에서 `npm run start`를 실행했을 때 콘솔에 아래와 같은 문법 오류가 발생합니다.

```Bash
> react-ssr@1.0.0 build:client
> if exist dist rmdir /s /q dist && webpack --config webpack.client.config.js

sh: -c: line 1: syntax error: unexpected end of file
```

크론이 올려주신 뼈대 코드의 원래 수정 내용은 아래와 같아요. 여기 작성된 내용을 보니 윈도우 환경에서의 명령어인 것 같은데, 혹시 아래와 같은 코드가 동작하지 않아서 이렇게 수정하신 것인지 궁금합니다.

```suggestion
    "build:client": "rm -rf dist && webpack --config webpack.client.config.js",
```

2024-10-11 07:25 UTC, seongjinme commented on src/client/main.js
> +hydrateRoot(document.getElementById("root"), <App movies={initialData.movies} />);
서버 측에서 `window.__INITIAL_DATA__` 전역변수의 초기화를 해주지 않았는데 이것을 `initialData`로 불러들이고 있어요. 원래대로라면 콘솔에 `TypeError`가 뜰 거에요. 그럼에도 코드를 실행해보면 이 에러가 뜨지 않는데요, 이는 즉 이 코드를 포함한 클라이언트 측의 전체 코드가 제대로 실행되고 있지 않다는 걸 의미합니다. 

이 문제를 해결하기 위해 제가 찾은 방법은 이렇습니다.

1. `src/server/routes/index.js`에 크론의 path 관련 수정 코드를 먼저 반영해주시고,
2. `src/constants.js`에 남겨드린 코멘트를 참고해서 상수를 분리해주신 다음,
3. 위에 말씀드린 전역변수의 초기화 작업을 반영해주시면 될 것 같습니다.

2024-10-11 07:25 UTC, seongjinme commented on src/constants.js
상수 선언부를 `src/` 경로 아래에 바로 두신 상태로 서버/클라이언트 양측에서 각각 `import`를 시켜주고 계세요. 이렇게 되면 Node.js 실행 환경을 전제하고 있는 `process.env.TMDB_TOKEN`가 클라이언트 사이드에서 로드되면서 `undefined` 에러가 콘솔에 뜨게 됩니다. Hydration 작업도 제대로 되지 않게 되어요. 번거로우시더라도 상수는 클라이언트, 서버 사이드로 각각 나누어 관리하시는 걸 추천드릴게요. 🙏

2024-10-11 07:25 UTC, seongjinme commented on src/server/routes/index.js
> +  const template = fs.readFileSync(templatePath, "utf8");
이 부분에 한해서, [크론이 수정한 뼈대 코드 내용](https://github.com/woowacourse/react-ssr/commit/8c9afb03c9eccd04f1c01f3233df2406c8aa6b75#diff-a3479d6ebd42689ed12cd282356bcbdb2ee016e4c8bce309bcac1ed28921914dR5)이 반영되어 있지 않아요. 이 부분과 `constants.js`의 상수 선언부를 모두 고쳐주셔야 원래 의도하셨던 hydration이 제대로 실행될 거에요.

2024-10-11 07:27 UTC, 00kang commented on package.json
> +    "build:client": "if exist dist rmdir /s /q dist && webpack --config webpack.client.config.js",
앗 이 부분을 pr에 남긴다는 걸 깜빡했네요! 
크론이 알려주신 뼈대 코드로는 윈도우 환경에서는 작동하지 않아서 수정하게 되었어요.

2024-10-12 08:12 UTC, 00kang commented on src/client/main.js
> +hydrateRoot(document.getElementById("root"), <App movies={initialData.movies} />);
우와아 아르
너무 깔끔하게 정리해주셔서 문제점이 뭔지 명확하게 알 수 있었어요 감사합니다 🙇

2024-10-12 08:18 UTC, 00kang commented on src/constants.js
분리하는게 번거롭다고 생각해서 src 하위에 위치했었는데, 분리해야만 hydration이 제대로 되는군요!

- [x] constants 분리하기 커밋 : https://github.com/woowacourse/react-ssr/pull/33/commits/8643eaca6415fa6f245f4b902049bb66c5471a88

2024-10-12 08:23 UTC, 00kang commented on src/server/routes/index.js
> +  const template = fs.readFileSync(templatePath, "utf8");
뼈대코드대로 수정했습니다! 그런데 `__dirname` 경로를 정의하지 않았는데 어떻게 index.html을 찾는걸까요? 

- [x] routes/index.html 뼈대 코드대로 수정하기 : https://github.com/woowacourse/react-ssr/pull/33/commits/8015eee8046db5153a766af42a05758126e834af

2024-10-13 04:23 UTC, seongjinme commented on src/client/main.js
> +hydrateRoot(document.getElementById("root"), <App movies={initialData.movies} />);
말씀대로 `initialData`에 할당해주는 작업을 의미합니다. 조금 더 풀어서 설명드리자면, 

1. 서버에서 생성한 데이터를 HTML에 포함시켜 클라이언트로 전달하고, 
2. 브라우저에서 이를 전역 객체(window)의 속성으로 설정하는 과정이라고 보시면 될 것 같아요.

2024-10-13 04:45 UTC, seongjinme commented on src/server/routes/index.js
> +  const template = fs.readFileSync(templatePath, "utf8");
`__dirname`은 Node 환경에서 제공되는 기본 환경변수입니다. 현재 실행 중인 스크립트 파일의 디렉토리 경로를 의미해요. 이 애플리케이션의 실행 경로는 `dist/server.js`이기 때문에, 해당 파일이 위치한 `dist/` 경로를 기준으로 `index.html`을 찾게 됩니다. 클라이언트/서버 코드가 빌드된 후의 `index.html`은 `dist/` 경로에 자리하게 되므로 Node 서버가 해당 파일을 올바르게 찾을 수 있게 되는 것이지요.

2024-10-13 05:30 UTC, seongjinme approved these changes
초코 고생 많으셨습니다. 팀플 등 여러 사정으로 바쁘셨을텐데도 피드백 드린 내용을 멋지게 잘 반영해 주셨네요 👍 1단계는 이만 머지하고, 2단계에서 다시 뵙도록 할게요!

아울러 댓글로 문의 주신 내용들에는 아래와 같이 답변 남겨드립니다.

> 그런데 전역변수 초기화라는게 initalData에 할당해주는 것 말고 해야 할 작업이 있는걸까요?

사실 "초기화"라는 단어가 조금 어색하게 느껴지긴 해요 😅 저는 이 개념에 대해서 "서버 측의 데이터를 HTML에 포함시켜 브라우저의 전역 객체(`window`) 속성으로 전달하는 작업"이라 이해하고 있습니다. 수정해주신 코드를 보니 TMDB에서 불러온 데이터를 `window.__INITIAL_DATA__`로 불러오도록 잘 처리해 주신 것 같습니다.

> 그런데 __dirname 경로를 정의하지 않았는데 어떻게 index.html을 찾는건지 의문이 생겨 질문드립니다.!

`__dirname`은 Node.js가 제공하는 기본 환경변수입니다. 현재 실행 중인 스크립트 파일의 절대경로를 의미해요. 이때 기준이 되는 경로는 working directory, 즉 프로젝트 루트 경로가 됩니다.

`package.json`에서 `npm run start`에 해당하는 스크립트 내용을 보면, 이 앱의 실행 경로가 `dist/server.js`로 되어 있어요. 따라서 해당 파일이 위치한 `dist/` 경로를 기준으로 `index.html`을 찾게 됩니다. `npm run start`는 사전에 클라이언트/서버 코드 빌드를 먼저 실행시키는데요, 이때 `index.html`은 `dist/` 경로로 옮겨집니다. 따라서 `path.resolve(__dirname, "index.html")`라고만 해도 `index.html`을 올바르게 찾을 수 있게 되는 것이지요.

2단계 미션도 화이팅입니다! 🙏

2024-10-13 05:30 UTC, merged