[서버 사이드 렌더링 - 2단계] 렛서(김다은) 미션 제출합니다.
woowacourse/react-ssr pull request #51
Opened 2024-10-19 13:48 UTC by llqqssttyy

## 👀 리뷰를 통한 생각 나눔

### 1. SSR 환경에서 웹 브라우저는 어떤 과정으로 하이드레이션(hydration)을 진행하는지 상세히 서술하시오.
> 💡 작성 요령: 서버에서 렌더링된 HTML과 클라이언트 측에서 React로 다시 그려질 때 발생할 수 있는 차이점은 무엇이며, 이로 인해 생길 수 있는 문제는 어떤 것이 있는지 고민해 보세요.

<br/>

### 2. 다음 두 가지 상황의 동작 과정을 비교해 설명하시오.
> 💡 작성 요령: 웹 브라우저는 처음에 서버에 요청할 때와 영화 목록을 요청할 때 반환 받는 값에는 어떤 차이가 있나요?

- 사용자가 처음 영화 목록 페이지에 접속할 때
- 하이드레이션 후, 사용자가 영화 목록에서 특정 영화를 클릭하여 상세 페이지로 이동할 때

<br/>

### 3. 다음 두 가지 상황의 동작 과정에서 라우팅의 차이점이 무엇인지 서술하시오.
> 💡 작성 요령: 각 상황에서 요청을 처리하는 주체가 무엇인지 생각해 보세요.

- 사용자가 https://주소/detail/12345와 같이 브라우저에 직접 입력한 뒤 페이지로 이동할 때
- 하이드레이션 후, 사용자가 영화 목록에서 특정 영화를 클릭하여 상세 페이지로 이동할 때

2024-10-20 14:24 UTC, greetings1012 requested changes
미션 수고하셨습니다!
다만, 제 컴퓨터에 pull받아 실행하면 아래와 같은 오류가 발생하더라구요.
한번 확인해보시면 좋을 것 같아요!

https://github.com/user-attachments/assets/134b1865-d717-4e2e-bc88-0ea9577f30ca

2024-10-20 14:54 UTC, greetings1012 commented on src/shared/apis/movies.js
> +
환경 변수는 webpack config에서 관리해주면 좋을 것 같아요!
여기서 서버 환경과 클라이언트 환경을 분리하면 나중에 프로젝트 크기가 커지면 너무 많은 곳에서 isServer를 호출해야 해요 😢

2024-10-20 16:30 UTC, llqqssttyy commented on src/shared/apis/movies.js
> +
[refactor: client env 설정](https://github.com/woowacourse/react-ssr/pull/51/commits/045d1e9f18d50e2453067ac8ce251b91431d4d0a)

반영했습니다!

2024-10-20 16:37 UTC, llqqssttyy commented
안녕하세요 파란~
말씀해주신 버그 픽스한 뒤 커밋했습니다. 아래에서 확인해주세요!

- 문제 상황: ssr로 리스트 페이지를 불러온 뒤 MovieItem 클릭으로 modal을 열었을 때 모달이 열리지 않는 문제
- 문제 원인: ssr에서 home 페이지 렌더 시 movieDetail을 null로 넣어줘 initialMovieDetail이 없어 reference 에러가 발생
- 문제 해결: csr로 모달을 열었을 때 데이터 패치가 일어나게 변경 및 데이터가 초기화되기 이전에 모달이 열리지 않도록 isLoading 초기값을 true로 변경

[fix: 초기화되지 않은 movieDetail 데이터로 인한 reference error](https://github.com/woowacourse/react-ssr/pull/51/commits/e53be038892a4766bb1cc17df1f501639d72846e)

2024-10-22 09:04 UTC, greetings1012 commented
확인해보니 페이지를 들어가서 처음 모달을 띄우면 정보를 불러오지 못해요.

https://github.com/user-attachments/assets/bbadd872-b841-425a-9bd0-ef8b2f9df95b


<img width="546" alt="image" src="https://github.com/user-attachments/assets/edb5dca7-8db6-42bf-b6c4-d7551555b869">
클라이언트 환경에서는 env를 정상적으로 불러오지 못하는 문제로 보여요!
아래 링크 참고해서 코드 수정하시면 좋을 것 같아요.
https://github.com/woowacourse/react-ssr/pull/48/commits/b0a4b255d4f5c2930e53460af7eb138c647f4b2b#diff-35094df584f8ebddbba9c8ac03bb293938d266abe188ecabb17e79b9fa3282d6

또한 한번 모달을 띄운 후 다시 닫고 다른 영화를 클릭하면 처음에 클릭했던 영화 정보가 그대로 계속 나오고 있어요.
클라이언트 환경에서 영화 상세 정보 데이터가 없다면 fetch하는 로직을 추가해주면 될 것 같아요!

두 개만 수정해 주시면 바로 머지하겠습니다 😄

2024-10-22 09:05 UTC, greetings1012 requested changes
확인해보니 페이지를 들어가서 처음 모달을 띄우면 정보를 불러오지 못해요.

https://github.com/user-attachments/assets/bbadd872-b841-425a-9bd0-ef8b2f9df95b


<img width="546" alt="image" src="https://github.com/user-attachments/assets/edb5dca7-8db6-42bf-b6c4-d7551555b869">

클라이언트 환경에서는 env를 정상적으로 불러오지 못하는 문제로 보여요!
아래 링크 참고해서 코드 수정하시면 좋을 것 같아요.

https://github.com/woowacourse/react-ssr/pull/48/commits/b0a4b255d4f5c2930e53460af7eb138c647f4b2b#diff-35094df584f8ebddbba9c8ac03bb293938d266abe188ecabb17e79b9fa3282d6

또한 한번 모달을 띄운 후 다시 닫고 다른 영화를 클릭하면 처음에 클릭했던 영화 정보가 그대로 계속 나오고 있어요.
클라이언트 환경에서 영화 상세 정보 데이터가 없다면 fetch하는 로직을 추가해주면 될 것 같아요!

두 개만 수정해 주시면 바로 머지하겠습니다 😄

2024-10-22 09:23 UTC, llqqssttyy commented
안녕하세요 파란~ 바쁜 시기에 고생이 많으십니다.
왜 파란 환경에서는 작동되지 않을까 생각해보니 env 변수의 이름이 달랐네요. 파란의 환경에 맞추어 process.env로 변경해서 올렸습니다.
[chore: env 설정 변경](https://github.com/woowacourse/react-ssr/pull/51/commits/e1b19a9e43beb2e50979300348cd8402b40d0e93)

그리고 csr 환경에서 데이터를 받아오지 않아 발생하는 문제는 앞선 코멘트에서 말씀드렸듯 픽스가 되었습니다!
env 때문에 fetch가 정상적으로 이루어지지 않으면서 확인하지 못한 것 같은데, 변경사항 적용 후에도 작동하지 않으면 말씀해주세요~
[fix: 초기화되지 않은 movieDetail 데이터로 인한 reference error](https://github.com/woowacourse/react-ssr/pull/51/commits/e53be038892a4766bb1cc17df1f501639d72846e)

2024-10-22 09:40 UTC, greetings1012 approved these changes
아하! 환경 변수 설정이 달라서 반복적으로 같은 오류가 발생했었네요.
제가 더 꼼꼼히 확인했어야 하는데... 죄송합니다  🙇

바로 Approve 드리겠습니다! 렛서도 바쁜 시기에 고생 많으셨어요 😁

2024-10-22 09:40 UTC, merged