[서버 사이드 렌더링 - 2단계] 파슬리(김윤아) 미션 제출합니다.
woowacourse/react-ssr pull request #59
Opened 2024-10-21 03:10 UTC by anttiey

안녕하세요, 치코! 이번 미션도 잘 부탁드립니다 🍀

<hr />

# 👀 리뷰를 통한 생각 나눔

## 1️⃣ SSR 환경에서 웹 브라우저는 어떤 과정으로 하이드레이션(hydration)을 진행하는지 상세히 서술하시오.
> ![image](https://github.com/user-attachments/assets/a33ffad6-9357-4cba-802c-bd2b229ecc55)

<br />

사용자가 웹 페이지에 접속하면 **서버에서 미리 생성된 정적 HTML을 브라우저로 전달**합니다. 이 HTML은 즉시 렌더링되지만 상호작용은 불가능합니다.

브라우저가 서버에서 받은 HTML을 렌더링하고 나면 **자바스크립트로 리액트와 같은 프레임워크를 실행**시킵니다. 리액트는 Virtual DOM을 생성해 **서버에서 전달받은 HTML과 비교하여 일치하는지 확인**합니다. 서버에서 생성된 HTML과 리액트가 생성한 DOM 간에 불일치가 있으면 예상치 못한 오류가 발생할 수 있기 때문에 하이드레이션 오류가 발생합니다.

이후 리액트는 DOM에 **이벤트 핸들러를 추가하고 상태 관리를 활성화**합니다. 따라서 클라이언트 측에서 상태 변화가 발생하면 리액트가 Virtual DOM을 사용해 변경 사항을 반영하고 필요한 부분만 다시 렌더링합니다.

## 2️⃣ 다음 두 가지 상황의 동작 과정을 비교해 설명하시오.
```
1. 사용자가 처음 영화 목록 페이지에 접속할 때
2. 하이드레이션 후, 사용자가 영화 목록에서 특정 영화를 클릭하여 상세 페이지로 이동할 때
```

사용자가 처음 영화 목록 페이지에 접속하면 브라우저가 서버에 요청을 보내고, 서버는 정적 HTML을 생성하여 브라우저에 응답합니다. 브라우저는 이 HTML을 즉시 렌더링하여 화면에 표시합니다. 하이드레이션이 완료된 후, 사용자가 특정 영화를 클릭하면 클라이언트 측에서 라우팅을 처리합니다. 영화 상세 정보는 클라이언트에서 API 호출로 비동기 요청을 통해 가져오며, 리액트가 상태를 업데이트해 화면에 표시합니다. 

정리해 보면, 처음 접속 시에는 **서버에서 전체 HTML을 받아 렌더링**하는 반면, 하이드레이션 후에는 **서버 요청 없이 클라이언트에서 페이지 이동과 데이터를 처리**합니다.

## 3️⃣ 다음 두 가지 상황의 동작 과정에서 라우팅의 차이점이 무엇인지 서술하시오.
```
1. 사용자가 https://주소/detail/12345와 같이 브라우저에 직접 입력한 뒤 페이지로 이동할 때
2. 하이드레이션 후, 사용자가 영화 목록에서 특정 영화를 클릭하여 상세 페이지로 이동할 때
```

사용자가 브라우저에 직접 경로를 입력해 페이지로 이동하면 서버에 새로운 요청이 보내지고, 서버는 해당 경로에 맞는 전체 HTML 페이지를 생성해 응답합니다. 반면, 하이드레이션 후 사용자가 영화 목록에서 영화를 클릭하면 리액트가 클라이언트 측에서 라우팅을 처리합니다. 클라이언트에서 경로를 변경하며 필요한 데이터는 비동기적으로 호출합니다.

직접 경로를 입력했을 때는 **서버에서 라우팅이 발생**해 전체 페이지가 새로 로드되지만, 하이드레이션 후에는 **클라이언트에서 라우팅을 처리**하여 페이지 일부를 변경합니다.

2024-10-22 03:00 UTC, jaeml06 requested changes
안녕하세요 파슬리! 우테코 마지막 미션 고생했어요!

2024-10-22 03:00 UTC, jaeml06 commented on src/client/components/Header.jsx
자세히 보기 버튼을 클릭해도 모달이 열려야 해요! 
그래도 나머지 경우에는 모달이 잘 열리는 것을 확인했으니 이번 미션에서는 수정을 하지는 않아도 괜찮아요!

2024-10-22 03:00 UTC, jaeml06 commented on src/client/pages/MovieDetail.jsx
> +}
크론이 수업 방식에서 설명한대로 TMDB에 직접 데이터를 가져오는 것이 아닌 서버를 통해 데이터를 가져오면 API 키를 노출하지 않아도 데이터를 가져올 수 있을 것 같아요

2024-10-22 03:03 UTC, jaeml06 commented on src/client/pages/MovieDetail.jsx
> +}
아니면 직접 TMDB에서 데이터를 가져오는 이점이 있을까요?

2024-10-23 02:08 UTC, anttiey commented on src/client/components/Header.jsx
이 부분을 놓쳤군요! 짚어 주셔서 감사합니다 😊 `자세히 보기` 버튼을 클릭했을 때도 모달이 열리도록 로직을 추가했습니다.

2024-10-23 02:18 UTC, anttiey commented on src/client/pages/MovieDetail.jsx
> +}
클라이언트에서 바로 TMDB 서버로 API 요청을 보내서 데이터를 가져와도 비용 문제가 발생하지 않고, 추가적으로 서버에 별도의 라우팅 로직을 만들지 않아도 되었기 때문에 이렇게 구현했습니다.

치코의 코멘트를 바탕으로 생각해 보니, 이미 SSR을 위한 서버가 구축되어 있는 상황이기 때문에 클라이언트에서 서버를 거쳐 데이터를 가져오면 중복된 패치 로직을 줄일 수 있다는 장점이 있겠네요! API 키와 같은 민감한 정보를 숨길 수 있다는 장점도 있겠고요. 서버에서 데이터를 처리하도록 변경했습니다 🙌🏻

2024-10-23 02:21 UTC, jaeml06 commented
고생했어요. 중간에 살펴보고 있었는데 실시간으로 변경중이어서 놀랐네요!
이만 머지하도록 할게요

2024-10-23 02:21 UTC, merged