[서버 사이드 렌더링 - 2단계] 헤일리(최혜림) 미션 제출합니다.
woowacourse/react-ssr pull request #72
Opened 2024-10-21 07:38 UTC by healim01

## 👀 리뷰를 통한 생각 나눔

2024-10-21 11:30 UTC, woowahan-cron commented
내일 미션 2단계 설문을 받을 예정인데 어떤 부분이 구체적으로 어려웠는지 적어주시면 후배 기수들을 위해 반영해볼게요~
마지막 피드백까지 그럼 잘 부탁해요 🙏 😉

2024-10-23 10:31 UTC, ss0526100 requested changes
헤일리 늦은 리뷰 죄송합니다 ㅜㅜ
리뷰가 늦어질 것 같으면 미리 말씀드렸어야 했는데 그러지 못해서 더 많이 기다리시게 만들었네요..

추가 질문 사항이 있습니다. 그 부분만 알려주시면 바로 머지하겠습니다.

고생하셨어요!!

2024-10-23 10:31 UTC, ss0526100 commented on views/index.html
>      <script src="./"></script>
(원본 코드지만..) 이 부분 때문에 불필요한 요청이 가고 있는 것 같아요! 참고하시면 좋을 것 같아요!
메인페이지에서는 서버라우팅이 되어있어서 문제가 없었지만 detail 페이지에서는 서버 라우팅 때문에 네트워크 에러가 발생해요

참고하시면 좋을 것 같습니다!
(이 코드를 지우면 정상 작동해요..!)
![image](https://github.com/user-attachments/assets/89edf3ff-cd57-402a-90c4-344c41e959f1)

2024-10-23 10:31 UTC, ss0526100 commented on src/server/routes/routes.jsx
> +      const { movies, movieDetail } = useLoaderData();
이런 방식으로 하이드레이션을 구현하셨군요..!

헤일리 덕분에 새로운 방식의 라우팅을 알아가네요 감사합니다

이러면 서버에서 불필요한 정보(movies,detail)를 보내주지 않아도 되어서 더 좋을 것 같네요!

2024-10-23 10:31 UTC, ss0526100 commented on src/server/routes/index.js
> +  let context = await handler.query(new Request('http://localhost:3000/'));
제가 이 코드를 이해하는데 시간이 걸려서 리뷰가 좀 늦어졌어요..

이 부분에 대해서 질문할 게 있습니다.

context를 만들기 위해서 'http://localhost:3000/'로 요청을 보내는 것 이라고 이해했는데요

그런데 사실 이 라우터 핸들러가 'http://localhost:3000/'로의 요청을 담당하는 것 같은데요.

그렇게 되면 router.get('/') 핸들러 실행=>콘텍스트 생성을 위해 쿼리 요청=>router.get('/') 핸들러 실행
이런 무한 루프에 빠지게 될 것 같다는게 제 생각입니다

이 부분을 조금 더 자세히 설명해주실 수 있으실까요?

2024-10-23 10:31 UTC, ss0526100 commented on src/server/main.js
> +app.use((_, res) => {
👍 👍

2024-10-23 11:09 UTC, healim01 commented on views/index.html
>      <script src="./"></script>
와.. 이거 때문이었군요... 덕분에 알았습니다

2024-10-24 04:49 UTC, healim01 commented on src/server/routes/index.js
> +  let context = await handler.query(new Request('http://localhost:3000/'));
해당 방식은 node 와 브라우저의 환경이 달라서 제공해준것인데요! context 를 위해 fetch 요청에 맞게 변형해서 전달하려고 이렇게 작업해봤습니다!! 

자세한 내용은 [공식문서](https://reactrouter.com/en/main/guides/ssr)에서 확인하실 수 있습니다!!

2024-10-24 04:55 UTC, ss0526100 commented on src/server/routes/index.js
> +  let context = await handler.query(new Request('http://localhost:3000/'));
알겠습니다!! 확인했어요~!

2024-10-24 04:58 UTC, ss0526100 commented
고생하셨습니다!! 머지할게요!! 남은 우테코 생활도 파이팅입니다!!

2024-10-24 04:58 UTC, ss0526100 approved these changes

2024-10-24 04:59 UTC, merged