[서버 사이드 렌더링 - 2단계] 초코(강다빈) 미션 제출합니다.
woowacourse/react-ssr pull request #76
Opened 2024-10-21 08:33 UTC by 00kang

안녕하세요 아르~ 2단계 미션 리뷰도 잘 부탁드립니다 :>

## 👀 리뷰를 통한 생각 나눔

### SSR 환경에서 웹 브라우저는 어떤 과정으로 하이드레이션(hydration)을 진행하는지 상세히 서술하시오.
💡 작성 요령: 서버에서 렌더링된 HTML과 클라이언트 측에서 React로 다시 그려질 때 발생할 수 있는 차이점은 무엇이며, 이로 인해 생길 수 있는 문제는 어떤 것이 있는지 고민해 보세요.

SSR 환경에서의 하이드레이션은 서버에서 생성된 HTML을 클라이언트의 React 컴포넌트로 활성화하는 과정입니다. 서버가 초기 HTML을 전송하면 브라우저가 이를 파싱하여 DOM을 구성합니다. 그 후 React 코드가 실행되어 서버의 DOM과 자체 가상 DOM을 비교하고, 이벤트 리스너를 연결하며 상태를 초기화합니다. 이 과정에서 서버와 클라이언트 간 렌더링 차이로 인한 문제가 발생할 수 있습니다. 예를 들어, 서버와 클라이언트의 시간이 다를 경우,, 

<br/>

### 다음 두 가지 상황의 동작 과정을 비교해 설명하시오.
💡 작성 요령: 웹 브라우저는 처음에 서버에 요청할 때와 영화 목록을 요청할 때 반환 받는 값에는 어떤 차이가 있나요?

**1) 사용자가 처음 영화 목록 페이지에 접속할 때**
- 서버에 전체 페이지 요청
- 서버는 전체 HTML, CSS, JS, 그리고 초기 상태 데이터 반환
- 클라이언트는 전체 페이지를 로드하고 하이드레이션 수행

**2) 하이드레이션 후, 사용자가 영화 목록에서 특정 영화를 클릭하여 상세 페이지로 이동할 때**
- 클라이언트에서 React Router가 URL 변경 처리
- 클라이언트에서 영화 상세 데이터만 API로 요청
- 서버는 JSON 데이터만 반환
- 클라이언트에서 받은 데이터로 UI 업데이트

위 두가지 동작의 주요 차이점은 초기 로드 시 전체 페이지를 받는 반면, 이후 네비게이션은 필요한 데이터만 받아 클라이언트에서 처리한다는 점입니다.
<br/>

### 다음 두 가지 상황의 동작 과정에서 라우팅의 차이점이 무엇인지 서술하시오.
💡 작성 요령: 각 상황에서 요청을 처리하는 주체가 무엇인지 생각해 보세요.

**1) 사용자가 https://주소/detail/12345와 같이 브라우저에 직접 입력한 뒤 페이지로 이동할 때**
- 서버가 요청을 처리
- 전체 페이지를 새로 렌더링하여 반환
- 클라이언트는 새 페이지를 로드하고 하이드레이션 수행

**2) 하이드레이션 후, 사용자가 영화 목록에서 특정 영화를 클릭하여 상세 페이지로 이동할 때**
- 클라이언트의 React Router가 요청을 처리
- 페이지 새로고침 없이 클라이언트에서 라우팅 처리
- 필요한 데이터만 API로 요청하여 UI 업데이트

2024-10-21 11:22 UTC, woowahan-cron commented
예를 들어, 서버와 클라이언트의 시간이 다를 경우,, ??

2024-10-22 02:22 UTC, seongjinme requested changes
안녕하세요 초코! 아르입니다. 
벌써 마지막 미션의 최종 단계네요. 고생 많으셨습니다 🙏 

하이드레이션 미스매치 문제도 없고, SSR로 초기 로드 후 CSR로의 전환도 잘 동작하는 것으로 보여요. 다만 코드를 보니, 데이터를 서버 사이드에서만 최초 1회 불러오게 되어 있네요. 클라이언트 사이드에서의 데이터 페칭은 구현되어 있지 않은 것 같습니다.

이로 인해 아래의 문제들이 발생하고 있어요.

1. 메인 페이지(`/`)로 접속한 뒤 영화 아이템을 클릭하면 `movieDetail`에 대한 `undefined`에러가 발생합니다.
2. 특정 영화 페이지(`/detail/{movieId}`)로 접속한 뒤 모달을 닫고, 다른 어떠한 영화를 클릭하더라도 처음 봤던 영화의 정보만 모달에 출력됩니다.

크론이 의도한 이번 미션의 요구사항 중에 "영화 아이템을 클릭할 때는 TMDB서버에서 JSON 데이터를 넘겨 받는다"는 내용이 있어요. 이걸 위해서는 앞서 말씀드린 클라이언트 데이터 페칭 로직을 추가해 주셔야 할 것 같습니다. 😢 

데모데이 준비로 바쁘시겠지만, 마지막까지 함께 화이팅 해보기로 해요 🙏

2024-10-22 02:22 UTC, seongjinme commented on src/client/App.jsx
> +      </Routes>
클라이언트 라우팅 처리를 깔끔하게 해주셨네요. 👍

2024-10-22 02:22 UTC, seongjinme commented on src/client/components/Header.jsx
> +  };
App 컴포넌트에서는 `react-router-dom`의 `useNavigate`로 라우팅을 처리해 주셨는데, 여기서는 `<a>`의 `href` 속성으로 링크를 직접 부여하신 뒤 `e.preventDefault()`로 브라우저 리프레시를 막고 계시네요.

클라이언트 사이드에서 링크를 이용한 라우팅을 처리하시려면 `useNavigate`나 `Link` 컴포넌트의 사용을 고려해보시면 좋겠습니다. 아래는 `react-router-dom`에서 제공하는 `Link` 컴포넌트에 대한 공식 문서입니다.

- https://reactrouter.com/en/main/components/link

2024-10-22 02:22 UTC, seongjinme commented on src/client/components/MovieItem.jsx
> +  };
이 부분에서도 Header 컴포넌트와 마찬가지로 클라이언트 사이드에서의 라우팅 적용을 고려해보세요 😄

2024-10-22 02:22 UTC, seongjinme commented on src/client/main.js
> +);
EOL 문제가 있네요 😮

2024-10-22 02:22 UTC, seongjinme commented on src/server/apis/movies.js
> +};
여기에도 EOL이... 😅

2024-10-22 02:22 UTC, seongjinme commented on webpack.server.config.js
> +  ],
서버 사이드의 웹팩 설정에 `react-router-dom`을 whitelist로 설정해 주셨는데, 혹시 어떤 이유로 이렇게 하셨는지 여쭈어도 될까요? 저도 잘 모르는 부분이어서 초코의 의견을 듣고 싶습니다 😄

2024-10-22 02:22 UTC, seongjinme commented on src/server/apis/movies.js
> +  const url = TMDB_MOVIE_DETAIL_URL + id;
사소한 부분이긴 하지만, 이 `url`에 `language=ko-KR` 파라미터가 빠져 있어서 모달 안의 콘텐츠가 영문으로 뜨네요 😅 미션 의도와는 큰 연관이 없는 부분이라 선택적으로 검토해 보시면 좋을 것 같습니다.

2024-10-24 01:28 UTC, 00kang commented on webpack.server.config.js
> +  ],
nodeExternals는 서버 번들 크기를 줄이기 위해 node_modules의 패키지들을 번들링하지 않아요. 하지만 react-router-dom은 서버사이드 렌더링(SSR)에서 라우팅을 처리하기 위해 꼭 필요한 패키지라서, 예외적으로 번들에 포함시켜야 해서 allowlist에 추가했어요!

추가하지 않아도 되는걸까요??

2024-10-24 01:53 UTC, seongjinme commented on webpack.server.config.js
> +  ],
`nodeExternals`는 말씀대로 서버 번들에서 node 패키지들을 제외시키는 옵션입니다. 하지만 그렇다고 해서 제외된 패키지들이 서버측 코드에서 실행되지 않는 건 아니에요. 서버가 Node.js 환경에서 돌아가기 때문에, 코드에서 import/require로 불러온 모듈은 모두 Node.js의 모듈 시스템을 통해 불러와집니다.

따라서 `allowlist`에 굳이 추가하지 않아도 `react-router-dom`은 정상 동작합니다. `nodeExternals`은 서버 번들 사이즈와 빌드 시간을 줄여주는 도구로 보시는게 좋을 것 같아요.

2024-10-24 02:11 UTC, 00kang commented on src/client/components/Header.jsx
> +  };
<Link> 방식으로 수정했습니다.
자료 제공 감사합니다 :)

2024-10-24 04:19 UTC, 00kang commented on webpack.server.config.js
> +  ],
아하 답변 감사합니다.! 다시 원래 코드로 수정했습니다 :>

2024-10-24 04:19 UTC, 00kang commented
안녕하세요 아르! 
최종 데모데이를 앞두고 있다보니 재리뷰요청이 늦어졌네요 😂
잘 작동하도록 리팩터링을 해보았으니 확인해주세요!

- [x] 메인페이지에서 모달 오픈 확인
- [x] url 직접 입력하여 모달 오픈 확인
- [x] 클라이언트 라우팅 Link 태그 활용하도록 수정

2024-10-24 05:18 UTC, seongjinme approved these changes
초코 고생 많으셨습니다! 최종 데모데이 앞두고 많이 바쁘셨을텐데 꼼꼼하게 잘 수정해 주셨네요.

내일로 다가온 데모데이, 그리고 얼마 남지 않은 교육기간 동안 모두 멋진 결과 얻으시길 기원하겠습니다. 🙏

2024-10-24 05:18 UTC, seongjinme commented on src/client/components/MovieItem.jsx
> +          <img src={starEmptyImg} className="star" alt="Star rating" />
꼼꼼하게 `alt` 속성도 챙겨주신 부분 좋습니다 👍

2024-10-24 05:18 UTC, merged