[서버 사이드 렌더링 - 1단계] 바다(손해영) 미션 제출합니다.
woowacourse/react-ssr pull request #9
Opened 2024-10-08 06:08 UTC by BadaHertz52

## 🍀 구현 
![스크린샷 2024-10-08 003505](https://github.com/user-attachments/assets/ac80cdae-1c86-437c-8648-726825b0a5e0)

## 👀 리뷰를 통한 생각 나눔
### SSR 렌더링 시 초기 렌더링 성능이 왜 유리할까?

CSR과 SSR 초기 렌더링 성능의 차이가 나는 이유는 서버에서 주는 HTML에 따른 DOM 생성 시점에 있습니다.

**DOM 생성 과정 자체는 SSR과 CSR에서 동일**하지만, SSR에서는 서버에서 **완성된 HTML을 먼저 제공**하고, 브라우저가 이를 즉시 파싱해 DOM을 생성할 수 있으므로 **초기 렌더링 속도가 빠릅니다**.( SSR에서는 DOM을 먼저 생성하고 JS 읽고 하이드레이션을 통해 동적 기능을 추가합니다)

반면에 CSR은  서버에서 받은 리소스로 HTML을 파싱해 DOM을 생성하는 과정에서 CSS,JS 파일을 다운도르 받아 이를 실행한 후 DOM을 다시 실행합니다. 

정리하면 SSR은 서버에서 HTML을 받을 후 바로 DOM을 생성해 렌더링 하지만, CSR은 서버에서 HTML을 받은 후 CSS,JS 코드 실행 후 DOM 생성을 완료해 렌더링 합니다.

### 서버에서 렌더링한 영화 목록을 어떻게 클라이언트에 데이터를 전달하고 브라우저에서는 어떤 작업을 수행할까?

우선  props로 데이터를 컴포넌트에 직접 전달하는 방식으로 미션을 진행했습니다. 

리액트는 상태와 props를 통해 데이터 흐름을 관리하기 때문에 전역 상태 대신 컴포넌트 기반 데이터 전달 방식을 사용했습니다. 또한 리액트를 사용하는 개발자들은 이런 데이터 흐름 관리에 익순해 유지 보수,확장성면에서도 좋다고 생각했습니다.  

```jsx

const renderedApp = renderToString(<App movieList={popularMovieList} />);
```

#### 리액트 로드시 가장 먼저 실행되는 작업 : hydrateRoot

리액트는 hydrateRoot을 통해 서버에서 미리 렌더링된 HTML과 리액트 컴포넌트를 결합하는 하이드레이션 작업을 수행합니다. 즉, 서버에서 렌더링된 HTML을 유지하거나 기존 DOM과 비교해 변경된 부분만 다시 렌더링하고, 이벤트와 상태 변화등 동적 상호작용을 추가합니다.

### **전역 객체 초기화 작업은 왜 진행해야 할까?**

서버에서 렌더링한 HTML과 클라이언트에서의 데이터가 일치하도록 보장하기 위해서 입니다.

 서버에서 렌더링 시 사용한 데이터를 **클라이언트에서도 동일하게 사용할 수 있도록 전역 변수로 전달합니다.**
만약 이 과정이 누락되거나 잘못되면, 서버와 클라이언트의 HTML 렌더링 결과가 달라져서 **Hydration 오류**가 발생할 수 있습니다.

2024-10-10 14:53 UTC, jinhokim98 requested changes
안녕하세요 바다! 1차 미션 고생많으셨습니다!
레벨 4 잘 소화하고 계신가요? 너무 할 일도 많고 정신도 없지만 파이팅 해봅시다💪💪
내용 읽어봤는데 충분히 잘 구현해주신 것 같아요. 하지만 몇 가지 궁금한 점이 있어서 일단 RC 드립니다!

2024-10-10 14:53 UTC, jinhokim98 commented on src/client/App.jsx
> +    </>
App에서 movieList를 사용하지 않고 Container와 Header로 바로 prop을 내려주잖아요!
지금은 구조가 단순해서 당장은 문제 없지만 앱이 복잡해진다면 필요한 컴포넌트에 바로 넣어주는 방식으로 구현하시는 것이 더 좋아보입니다😄

2024-10-10 14:53 UTC, jinhokim98 commented on src/client/components/Footer.jsx
> +  );
footer를 client 컴포넌트화 시킨 이유가 궁금합니다

2024-10-10 14:53 UTC, jinhokim98 commented on src/client/components/MovieItem.jsx
> +function MovieItem({ rate, title, thumbnailUrl, onClick }) {
혹시 onClick을 따로 빼준 이유가 있을까요?
사용처에서 onClick prop이 보이지 않아서요😅😅

2024-10-10 14:53 UTC, jinhokim98 commented on src/client/main.js
> +const movieList = window.__INITIAL_DATA__.movieList;
저는 initial data를 사용하지 않아도 에러가 나지 않았어요 (제가 이상하게 구현한 것 일수도 있습니다🫠)

initial data을 사용하지 않으면 에러가 발생한다고 하셔서 어떻게 나는지 궁금해서 여쭤봅니다!

2024-10-10 14:53 UTC, jinhokim98 commented on src/client/components/Container.jsx
> +              <li key={id}>
key index가 아닌 고유값 넣어주신 것 너무 좋습니다👍

2024-10-10 14:53 UTC, jinhokim98 commented on src/server/routes/index.js
> +  const renderedApp = renderToString(<App movieList={popularMovieList} />);
renderToString은 무슨 역할을 할까요?

2024-10-11 02:08 UTC, BadaHertz52 commented on src/client/App.jsx
> +    </>
### props로 전달한 이유
SSR시, 영화 데이터가 필요한 컴포넌트들을 index.html에서 적절한 위치에 `renderToString`을 사용해 삽입할 수 도 있어요. 그렇게 하지 않고 App을 서버에서 render하게 한 이유는 index.html에서 적절한 위치를 표시하고 해당 표시 문구와 `renderToString`으로 컴포넌트 렌더링된 결과를 바꾸는 것보다 App에서 레이아웃을 한번에 관리하고 렌더링하는게 개발자 입장에서 더 편할 거라고 생각했어요. 

### props 드릴링 문제 
아마 쿠기가 우려하시는 부분은 props 드릴링같아요.  만약 쿠키가 이야기한 상황이 생긴다면, 전역 상태를 사용할 것 같아요. 영화 목록 하나의 데이터를 가지고 모든 컴포넌트에 사용하기 때문이에요. 

다만 현재 프로젝트에 적용하지 않은 이유는 현재 프로젝트 사이즈에 비해 전역 상태 관리하는 것은 과하다고 느껴졌어요.  그리고 이번 미션인 SSR에 집중하고 싶었어요.

2024-10-11 02:09 UTC, BadaHertz52 commented on src/client/components/Footer.jsx
> +  );
위에서 언급한대로, html 기본 뼈대 코드외의 크라이어트단 코드는 클라이언트에서 관리하도록 했어요

2024-10-11 02:14 UTC, BadaHertz52 commented on src/client/components/MovieItem.jsx
> +function MovieItem({ rate, title, thumbnailUrl, onClick }) {
현재 1단계 미션 요구사항 중 onClick을 통해 일어나는 이벤트 구현이 없어요. 사용하지 않는데 props로 주는 것은 코드를 보는 다른 개발자에게 혼란을 줄거 같아요. 만약 click 이벤트를 구현해야한다면, 그때 props로 넣어 주면 된다고 생각해요

2024-10-11 02:18 UTC, BadaHertz52 commented on src/client/main.js
> +const movieList = window.__INITIAL_DATA__.movieList;
서버에서 HTML을 주고, 다시 클라이언트에서 렌더링 같을 비교한다고 하더라구요.
그때 서버에서 준 것과 클라이언트에서 렌더링한 것 사이에 차이가 있으면 hydration 오류가 나요.

또한 저는 App에서 movieList props를 받아야해서 client/main.js에 오류가 나지 않도록 전역 객체로 movieList에 대한 데이터 값을 props로 넘겨주고 있어요.

2024-10-11 02:19 UTC, BadaHertz52 commented on src/server/routes/index.js
> +  const renderedApp = renderToString(<App movieList={popularMovieList} />);
컴포넌트 렌더링 값을 문자열로 반환해주는 것으로 알고 있어요

2024-10-12 03:01 UTC, jinhokim98 commented on src/client/App.jsx
> +    </>
아하 그렇게 생각할 수도 있네요! 확실한 의도를 갖고 구현하신 점 좋습니다!

2024-10-12 03:03 UTC, jinhokim98 commented on src/client/components/Footer.jsx
> +  );
변경되지 않을 html이어서 서버에서 만들어서 주는 것이 더 유리할 것이라 생각했었어요.
그런데 어제 크론이 변경한 코드를 보니 index.html이 다 사라져있네요😅😅

2024-10-12 03:05 UTC, jinhokim98 commented on src/client/main.js
> +const movieList = window.__INITIAL_DATA__.movieList;
자세한 설명 감사합니다! 저도 2단계에서 테스트 해보겠습니다!

2024-10-12 03:08 UTC, jinhokim98 approved these changes
안녕하세요 바다!
리뷰하면서 바다의 확실한 주관과 자세한 설명까지 들을 수 있어서 너무 유익했습니다.
충분한 것 같아 merge 하겠습니다!
그럼 2단계 미션도 파이팅이에요👍

2024-10-12 03:08 UTC, merged